-- FoodLog Table Notes safety and group-decision foundation.
-- Additive migration only. Apply to an isolated Supabase branch first.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

alter table if exists public.restaurants
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text,
  add column if not exists import_batch_id uuid;

alter table if exists public.dishes
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table if exists public.restaurant_photos
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table if exists public.restaurant_ratings
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table if exists public.dish_ratings
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table if exists public.playlists
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text,
  add column if not exists member_restaurant_ids uuid[] not null default '{}';

create index if not exists restaurants_active_updated_idx
  on public.restaurants (updated_at desc)
  where deleted_at is null;
create unique index if not exists restaurants_import_batch_name_location_unique
  on public.restaurants (import_batch_id, lower(name), lower(location))
  where import_batch_id is not null;
create index if not exists dishes_active_restaurant_idx
  on public.dishes (restaurant_id, updated_at desc)
  where deleted_at is null;
create index if not exists restaurant_photos_active_restaurant_idx
  on public.restaurant_photos (restaurant_id, created_at desc)
  where deleted_at is null;

create or replace function public.is_foodlog_owner()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'danielhanna0001@gmail.com'
$$;

create or replace function public.is_approved_editor()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists (
    select 1
    from public.approved_users
    where lower(email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
$$;

revoke all on function public.is_foodlog_owner() from public;
revoke all on function public.is_approved_editor() from public;
grant execute on function public.is_foodlog_owner() to authenticated;
grant execute on function public.is_approved_editor() to authenticated;

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null check (action in ('create', 'edit', 'trash', 'restore', 'picker', 'import', 'admin')),
  actor_email text not null default '',
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_log_entity_idx
  on public.activity_log (entity_type, entity_id, created_at desc);
create index if not exists activity_log_actor_idx
  on public.activity_log (lower(actor_email), created_at desc);

alter table public.activity_log enable row level security;
revoke all on public.activity_log from anon, authenticated;
grant select on public.activity_log to authenticated;

drop policy if exists "Editors can read relevant activity" on public.activity_log;
create policy "Editors can read relevant activity"
on public.activity_log for select
to authenticated
using (
  public.is_foodlog_owner()
  or lower(actor_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
);

create or replace function private.log_foodlog_row_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  old_json jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  new_json jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  row_json jsonb := coalesce(new_json, old_json);
  record_id text;
  event_action text;
  actor text := lower(coalesce((select auth.jwt() ->> 'email'), 'system'));
begin
  record_id := coalesce(
    row_json ->> 'id',
    row_json ->> 'name',
    concat_ws(':', row_json ->> 'restaurant_id', row_json ->> 'rater_email'),
    concat_ws(':', row_json ->> 'dish_id', row_json ->> 'rater_email'),
    'unknown'
  );

  if tg_argv[0] in ('decision_sessions', 'decision_candidates', 'decision_votes') then
    event_action := 'picker';
  elsif tg_argv[0] in ('approved_users', 'pending_approvals') then
    event_action := 'admin';
  elsif tg_op = 'INSERT' and nullif(row_json ->> 'import_batch_id', '') is not null then
    event_action := 'import';
  elsif tg_op = 'INSERT' then
    event_action := 'create';
  elsif old_json ->> 'deleted_at' is null and new_json ->> 'deleted_at' is not null then
    event_action := 'trash';
  elsif old_json ->> 'deleted_at' is not null and new_json ->> 'deleted_at' is null then
    event_action := 'restore';
  else
    event_action := 'edit';
  end if;

  insert into public.activity_log (
    entity_type,
    entity_id,
    action,
    actor_email,
    before_state,
    after_state
  )
  values (tg_argv[0], record_id, event_action, actor, old_json, new_json);

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function private.log_foodlog_row_change() from public, anon, authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'restaurants',
    'dishes',
    'restaurant_photos',
    'restaurant_ratings',
    'dish_ratings',
    'playlists'
  ]
  loop
    if to_regclass('public.' || table_name) is not null then
      execute format('drop trigger if exists foodlog_activity on public.%I', table_name);
      execute format(
        'create trigger foodlog_activity after insert or update on public.%I for each row execute function private.log_foodlog_row_change(%L)',
        table_name,
        table_name
      );
    end if;
  end loop;
end
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['approved_users', 'pending_approvals']
  loop
    if to_regclass('public.' || table_name) is not null then
      execute format('drop trigger if exists foodlog_admin_activity on public.%I', table_name);
      execute format(
        'create trigger foodlog_admin_activity after insert or update or delete on public.%I for each row execute function private.log_foodlog_row_change(%L)',
        table_name,
        table_name
      );
    end if;
  end loop;
end
$$;

-- Replace overlapping content policies with one explicit policy per operation.
do $$
declare
  policy_row record;
begin
  for policy_row in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'restaurants',
        'dishes',
        'restaurant_photos',
        'restaurant_ratings',
        'dish_ratings',
        'playlists'
      )
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_row.policyname,
      policy_row.schemaname,
      policy_row.tablename
    );
  end loop;
end
$$;

alter table public.restaurants enable row level security;
alter table public.dishes enable row level security;
alter table public.restaurant_photos enable row level security;
alter table public.restaurant_ratings enable row level security;
alter table public.dish_ratings enable row level security;
alter table public.playlists enable row level security;

grant select on public.restaurants, public.dishes, public.restaurant_photos,
  public.restaurant_ratings, public.dish_ratings, public.playlists
to anon, authenticated;
grant insert, update on public.restaurants, public.dishes, public.restaurant_photos,
  public.restaurant_ratings, public.dish_ratings, public.playlists
to authenticated;
revoke delete on public.restaurants, public.dishes, public.restaurant_photos,
  public.restaurant_ratings, public.dish_ratings, public.playlists
from anon, authenticated;

create policy "Public can read active restaurants"
on public.restaurants for select to anon, authenticated
using (deleted_at is null);
create policy "Editors can read recoverable restaurants"
on public.restaurants for select to authenticated
using (
  deleted_at is not null
  and public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
);
create policy "Approved editors can add restaurants"
on public.restaurants for insert to authenticated
with check (public.is_approved_editor() and deleted_at is null);
create policy "Approved editors can update restaurants"
on public.restaurants for update to authenticated
using (
  public.is_approved_editor()
  and (
    deleted_at is null
    or public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
)
with check (public.is_approved_editor());

create policy "Public can read active dishes"
on public.dishes for select to anon, authenticated
using (
  deleted_at is null
  and exists (
    select 1 from public.restaurants
    where restaurants.id = dishes.restaurant_id
      and restaurants.deleted_at is null
  )
);
create policy "Editors can read recoverable dishes"
on public.dishes for select to authenticated
using (
  deleted_at is not null
  and public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
);
create policy "Approved editors can add dishes"
on public.dishes for insert to authenticated
with check (
  public.is_approved_editor()
  and deleted_at is null
  and exists (
    select 1 from public.restaurants
    where restaurants.id = dishes.restaurant_id
      and restaurants.deleted_at is null
  )
);
create policy "Approved editors can update dishes"
on public.dishes for update to authenticated
using (
  public.is_approved_editor()
  and (
    deleted_at is null
    or public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
)
with check (public.is_approved_editor());

create policy "Public can read active restaurant photos"
on public.restaurant_photos for select to anon, authenticated
using (
  deleted_at is null
  and exists (
    select 1 from public.restaurants
    where restaurants.id = restaurant_photos.restaurant_id
      and restaurants.deleted_at is null
  )
);
create policy "Editors can read recoverable restaurant photos"
on public.restaurant_photos for select to authenticated
using (
  deleted_at is not null
  and public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
);
create policy "Approved editors can add restaurant photos"
on public.restaurant_photos for insert to authenticated
with check (
  public.is_approved_editor()
  and deleted_at is null
  and exists (
    select 1 from public.restaurants
    where restaurants.id = restaurant_photos.restaurant_id
      and restaurants.deleted_at is null
  )
);
create policy "Approved editors can update restaurant photos"
on public.restaurant_photos for update to authenticated
using (
  public.is_approved_editor()
  and (
    deleted_at is null
    or public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
)
with check (public.is_approved_editor());

create policy "Public can read active restaurant ratings"
on public.restaurant_ratings for select to anon, authenticated
using (
  deleted_at is null
  and exists (
    select 1 from public.restaurants
    where restaurants.id = restaurant_ratings.restaurant_id
      and restaurants.deleted_at is null
  )
);
create policy "Editors can read recoverable restaurant ratings"
on public.restaurant_ratings for select to authenticated
using (
  deleted_at is not null
  and public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
);
create policy "Editors can add their restaurant rating"
on public.restaurant_ratings for insert to authenticated
with check (
  public.is_approved_editor()
  and deleted_at is null
  and lower(rater_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
);
create policy "Editors can update their restaurant rating"
on public.restaurant_ratings for update to authenticated
using (
  public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(rater_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
)
with check (public.is_approved_editor());

create policy "Public can read active dish ratings"
on public.dish_ratings for select to anon, authenticated
using (
  deleted_at is null
  and exists (
    select 1
    from public.dishes
    join public.restaurants on restaurants.id = dishes.restaurant_id
    where dishes.id = dish_ratings.dish_id
      and dishes.deleted_at is null
      and restaurants.deleted_at is null
  )
);
create policy "Editors can read recoverable dish ratings"
on public.dish_ratings for select to authenticated
using (
  deleted_at is not null
  and public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
);
create policy "Editors can add their dish rating"
on public.dish_ratings for insert to authenticated
with check (
  public.is_approved_editor()
  and deleted_at is null
  and lower(rater_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
);
create policy "Editors can update their dish rating"
on public.dish_ratings for update to authenticated
using (
  public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(rater_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
)
with check (public.is_approved_editor());

create policy "Public can read active playlists"
on public.playlists for select to anon, authenticated
using (deleted_at is null);
create policy "Editors can read recoverable playlists"
on public.playlists for select to authenticated
using (
  deleted_at is not null
  and public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
);
create policy "Approved editors can add playlists"
on public.playlists for insert to authenticated
with check (public.is_approved_editor() and deleted_at is null);
create policy "Approved editors can update playlists"
on public.playlists for update to authenticated
using (
  public.is_approved_editor()
  and (
    deleted_at is null
    or public.is_foodlog_owner()
    or lower(deleted_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
)
with check (public.is_approved_editor());

-- Save each journal record and the current editor's rating/review in one transaction.
-- Media is uploaded before the dish RPC. If this transaction fails, no committed row
-- can reference the new path, so the client may safely remove only that new orphan.
create or replace function public.save_restaurant_with_rating(
  p_restaurant jsonb,
  p_rating numeric default null,
  p_restaurant_id uuid default null
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $save_restaurant$
declare
  saved_id uuid := p_restaurant_id;
  actor_email text := lower(coalesce((select auth.jwt() ->> 'email'), ''));
  actor_name text := coalesce(nullif(p_restaurant ->> 'updated_by', ''), split_part(actor_email, '@', 1));
begin
  if not public.is_approved_editor() then
    raise exception 'Only approved editors can save restaurants.';
  end if;

  if nullif(trim(p_restaurant ->> 'name'), '') is null then
    raise exception 'Restaurant name is required.';
  end if;

  if saved_id is null then
    insert into public.restaurants (
      name, location, cuisine, playlist, playlists, price, maps, notes, visited,
      updated_at, updated_by
    )
    values (
      trim(p_restaurant ->> 'name'),
      coalesce(p_restaurant ->> 'location', ''),
      coalesce(p_restaurant ->> 'cuisine', ''),
      coalesce(p_restaurant ->> 'playlist', ''),
      coalesce(
        array(select jsonb_array_elements_text(coalesce(p_restaurant -> 'playlists', '[]'::jsonb))),
        '{}'::text[]
      ),
      coalesce(p_restaurant ->> 'price', '$$'),
      coalesce(p_restaurant ->> 'maps', ''),
      coalesce(p_restaurant ->> 'notes', ''),
      coalesce(
        array(select jsonb_array_elements_text(coalesce(p_restaurant -> 'visited', '[]'::jsonb))),
        '{}'::text[]
      ),
      now(),
      actor_name
    )
    returning id into saved_id;
  else
    update public.restaurants
    set
      name = trim(p_restaurant ->> 'name'),
      location = coalesce(p_restaurant ->> 'location', ''),
      cuisine = coalesce(p_restaurant ->> 'cuisine', ''),
      playlist = coalesce(p_restaurant ->> 'playlist', ''),
      playlists = coalesce(
        array(select jsonb_array_elements_text(coalesce(p_restaurant -> 'playlists', '[]'::jsonb))),
        '{}'::text[]
      ),
      price = coalesce(p_restaurant ->> 'price', '$$'),
      maps = coalesce(p_restaurant ->> 'maps', ''),
      notes = coalesce(p_restaurant ->> 'notes', ''),
      visited = coalesce(
        array(select jsonb_array_elements_text(coalesce(p_restaurant -> 'visited', '[]'::jsonb))),
        '{}'::text[]
      ),
      updated_at = now(),
      updated_by = actor_name
    where id = saved_id and deleted_at is null;

    if not found then
      raise exception 'Restaurant is unavailable or in Trash.';
    end if;
  end if;

  if p_rating is null then
    update public.restaurant_ratings
    set deleted_at = now(), deleted_by = actor_email
    where restaurant_id = saved_id
      and lower(rater_email) = actor_email
      and deleted_at is null;
  else
    if p_rating < 0.5 or p_rating > 5 then
      raise exception 'Rating must be between 0.5 and 5.';
    end if;
    insert into public.restaurant_ratings (
      restaurant_id, rater_email, rater_name, rating, deleted_at, deleted_by
    )
    values (saved_id, actor_email, actor_name, p_rating, null, null)
    on conflict (restaurant_id, rater_email)
    do update set
      rater_name = excluded.rater_name,
      rating = excluded.rating,
      deleted_at = null,
      deleted_by = null;
  end if;

  return saved_id;
end;
$save_restaurant$;

create or replace function public.save_dish_with_rating(
  p_restaurant_id uuid,
  p_dish jsonb,
  p_rating numeric default null,
  p_review_notes text default '',
  p_dish_id uuid default null
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  saved_id uuid := p_dish_id;
  actor_email text := lower(coalesce((select auth.jwt() ->> 'email'), ''));
  actor_name text := coalesce(nullif(p_dish ->> 'updated_by', ''), split_part(actor_email, '@', 1));
begin
  if not public.is_approved_editor() then
    raise exception 'Only approved editors can save dishes.';
  end if;

  if nullif(trim(p_dish ->> 'name'), '') is null then
    raise exception 'Dish name is required.';
  end if;

  if saved_id is null then
    insert into public.dishes (
      restaurant_id, name, rating, liked_by, notes, photo_path, updated_at, updated_by
    )
    values (
      p_restaurant_id,
      trim(p_dish ->> 'name'),
      0,
      coalesce(
        array(select jsonb_array_elements_text(coalesce(p_dish -> 'liked_by', '[]'::jsonb))),
        '{}'::text[]
      ),
      '',
      coalesce(p_dish ->> 'photo_path', ''),
      now(),
      actor_name
    )
    returning id into saved_id;
  else
    update public.dishes
    set
      name = trim(p_dish ->> 'name'),
      liked_by = coalesce(
        array(select jsonb_array_elements_text(coalesce(p_dish -> 'liked_by', '[]'::jsonb))),
        '{}'::text[]
      ),
      photo_path = coalesce(p_dish ->> 'photo_path', ''),
      updated_at = now(),
      updated_by = actor_name
    where id = saved_id
      and restaurant_id = p_restaurant_id
      and deleted_at is null;

    if not found then
      raise exception 'Dish is unavailable or in Trash.';
    end if;
  end if;

  if p_rating is null then
    update public.dish_ratings
    set deleted_at = now(), deleted_by = actor_email
    where dish_id = saved_id
      and lower(rater_email) = actor_email
      and deleted_at is null;
  else
    if p_rating < 0.5 or p_rating > 5 then
      raise exception 'Rating must be between 0.5 and 5.';
    end if;
    insert into public.dish_ratings (
      dish_id, rater_email, rater_name, rating, notes, deleted_at, deleted_by
    )
    values (
      saved_id, actor_email, actor_name, p_rating, coalesce(p_review_notes, ''), null, null
    )
    on conflict (dish_id, rater_email)
    do update set
      rater_name = excluded.rater_name,
      rating = excluded.rating,
      notes = excluded.notes,
      deleted_at = null,
      deleted_by = null;
  end if;

  return saved_id;
end;
$$;

-- Playlist membership and its recoverable lookup row change together.
create or replace function public.rename_foodlog_playlist(p_from text, p_to text)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  from_name text := trim(p_from);
  to_name text := trim(p_to);
begin
  if not public.is_approved_editor() then
    raise exception 'Only approved editors can rename playlists.';
  end if;
  if from_name = '' or to_name = '' then
    raise exception 'Playlist name is required.';
  end if;
  if exists (select 1 from public.playlists where name = to_name and deleted_at is null) then
    raise exception 'A playlist with that name already exists.';
  end if;

  update public.restaurants
  set
    playlists = array_replace(coalesce(playlists, '{}'::text[]), from_name, to_name),
    playlist = case when playlist = from_name then to_name else playlist end,
    updated_at = now()
  where deleted_at is null and from_name = any(coalesce(playlists, '{}'::text[]));

  update public.playlists
  set name = to_name, deleted_at = null, deleted_by = null
  where name = from_name and deleted_at is null;

  if not found then
    insert into public.playlists (name) values (to_name)
    on conflict (name) do update set deleted_at = null, deleted_by = null;
  end if;
end;
$$;

create or replace function public.trash_foodlog_playlist(p_name text)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  playlist_name text := trim(p_name);
  member_ids uuid[];
  actor_email text := lower(coalesce((select auth.jwt() ->> 'email'), ''));
begin
  if not public.is_approved_editor() then
    raise exception 'Only approved editors can move playlists to Trash.';
  end if;

  select coalesce(array_agg(id), '{}'::uuid[])
  into member_ids
  from public.restaurants
  where deleted_at is null and playlist_name = any(coalesce(playlists, '{}'::text[]));

  update public.restaurants
  set
    playlists = array_remove(coalesce(playlists, '{}'::text[]), playlist_name),
    playlist = coalesce(
      (array_remove(coalesce(playlists, '{}'::text[]), playlist_name))[1],
      ''
    ),
    updated_at = now()
  where id = any(member_ids);

  update public.playlists
  set deleted_at = now(), deleted_by = actor_email, member_restaurant_ids = member_ids
  where name = playlist_name and deleted_at is null;

  if not found then
    insert into public.playlists (name, deleted_at, deleted_by, member_restaurant_ids)
    values (playlist_name, now(), actor_email, member_ids)
    on conflict (name) do update set
      deleted_at = excluded.deleted_at,
      deleted_by = excluded.deleted_by,
      member_restaurant_ids = excluded.member_restaurant_ids;
  end if;
end;
$$;

create or replace function public.restore_foodlog_playlist(p_name text)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  playlist_name text := trim(p_name);
  member_ids uuid[];
begin
  if not public.is_approved_editor() then
    raise exception 'Only approved editors can restore playlists.';
  end if;

  select member_restaurant_ids
  into member_ids
  from public.playlists
  where name = playlist_name and deleted_at is not null
  for update;

  if not found then
    raise exception 'Playlist is not available in Trash.';
  end if;

  update public.restaurants
  set
    playlists = case
      when playlist_name = any(coalesce(playlists, '{}'::text[])) then playlists
      else array_append(coalesce(playlists, '{}'::text[]), playlist_name)
    end,
    playlist = case
      when coalesce(array_length(playlists, 1), 0) = 0 then playlist_name
      else playlist
    end,
    updated_at = now()
  where id = any(coalesce(member_ids, '{}'::uuid[]))
    and deleted_at is null;

  update public.playlists
  set deleted_at = null, deleted_by = null, member_restaurant_ids = '{}'::uuid[]
  where name = playlist_name;
end;
$$;

revoke all on function public.save_restaurant_with_rating(jsonb, numeric, uuid) from public;
revoke all on function public.save_dish_with_rating(uuid, jsonb, numeric, text, uuid) from public;
revoke all on function public.rename_foodlog_playlist(text, text) from public;
revoke all on function public.trash_foodlog_playlist(text) from public;
revoke all on function public.restore_foodlog_playlist(text) from public;
grant execute on function public.save_restaurant_with_rating(jsonb, numeric, uuid) to authenticated;
grant execute on function public.save_dish_with_rating(uuid, jsonb, numeric, text, uuid) to authenticated;
grant execute on function public.rename_foodlog_playlist(text, text) to authenticated;
grant execute on function public.trash_foodlog_playlist(text) to authenticated;
grant execute on function public.restore_foodlog_playlist(text) to authenticated;

-- Public group count without exposing which friend saved a place.
create or replace function public.get_want_to_go_totals()
returns table (restaurant_id uuid, want_to_go_count bigint)
language sql
stable
security definer
set search_path = ''
as $$
  select want.restaurant_id, count(*)::bigint
  from public.restaurant_want_to_go as want
  join public.restaurants on restaurants.id = want.restaurant_id
  where restaurants.deleted_at is null
  group by want.restaurant_id
$$;

revoke all on function public.get_want_to_go_totals() from public;
grant execute on function public.get_want_to_go_totals() to anon, authenticated;

-- A validated import enters the database in one transaction. Media is uploaded first by the
-- preview client and is removed only if this function fails, so a retry cannot create duplicates.
create or replace function public.import_foodlog_batch(p_batch_id uuid, p_payload jsonb)
returns integer
language plpgsql
security invoker
set search_path = ''
as $import_batch$
declare
  restaurant_json jsonb;
  dish_json jsonb;
  photo_json jsonb;
  restaurant_id uuid;
  dish_id uuid;
  imported_count integer := 0;
  actor_email text := lower(coalesce((select auth.jwt() ->> 'email'), ''));
  actor_name text := split_part(actor_email, '@', 1);
  rating_json jsonb;
begin
  if not public.is_approved_editor() then
    raise exception 'Only approved editors can import.';
  end if;
  if jsonb_typeof(p_payload) <> 'array' then
    raise exception 'Import payload must be an array.';
  end if;
  if exists (select 1 from public.restaurants where import_batch_id = p_batch_id) then
    return 0;
  end if;

  for restaurant_json in select value from jsonb_array_elements(p_payload)
  loop
    insert into public.restaurants (
      name, location, cuisine, playlist, playlists, price, maps, notes, visited,
      updated_at, updated_by, import_batch_id
    )
    values (
      trim(restaurant_json ->> 'name'),
      trim(restaurant_json ->> 'location'),
      trim(restaurant_json ->> 'cuisine'),
      coalesce(restaurant_json -> 'playlists' ->> 0, ''),
      coalesce(array(select jsonb_array_elements_text(coalesce(restaurant_json -> 'playlists', '[]'::jsonb))), '{}'::text[]),
      coalesce(restaurant_json ->> 'price', '$$'),
      coalesce(restaurant_json ->> 'maps', ''),
      coalesce(restaurant_json ->> 'notes', ''),
      coalesce(array(select jsonb_array_elements_text(coalesce(restaurant_json -> 'visited', '[]'::jsonb))), '{}'::text[]),
      now(),
      actor_name,
      p_batch_id
    )
    returning id into restaurant_id;

    for photo_json in select value from jsonb_array_elements(coalesce(restaurant_json -> 'photos', '[]'::jsonb))
    loop
      if nullif(photo_json ->> 'photoPath', '') is not null then
        insert into public.restaurant_photos (restaurant_id, photo_path)
        values (restaurant_id, photo_json ->> 'photoPath');
      end if;
    end loop;

    for dish_json in select value from jsonb_array_elements(coalesce(restaurant_json -> 'dishes', '[]'::jsonb))
    loop
      insert into public.dishes (
        restaurant_id, name, rating, liked_by, notes, photo_path, updated_at, updated_by
      )
      values (
        restaurant_id,
        trim(dish_json ->> 'name'),
        0,
        coalesce(array(select jsonb_array_elements_text(coalesce(dish_json -> 'likedBy', '[]'::jsonb))), '{}'::text[]),
        '',
        coalesce(dish_json ->> 'photoPath', ''),
        now(),
        actor_name
      )
      returning id into dish_id;

      rating_json := coalesce(dish_json -> 'ratings' -> 0, null);
      if rating_json is not null and coalesce((rating_json ->> 'rating')::numeric, 0) >= 0.5 then
        insert into public.dish_ratings (dish_id, rater_email, rater_name, rating, notes)
        values (
          dish_id,
          actor_email,
          actor_name,
          (rating_json ->> 'rating')::numeric,
          coalesce(rating_json ->> 'notes', '')
        );
      end if;
    end loop;

    rating_json := coalesce(restaurant_json -> 'ratings' -> 0, null);
    if rating_json is not null and coalesce((rating_json ->> 'rating')::numeric, 0) >= 0.5 then
      insert into public.restaurant_ratings (restaurant_id, rater_email, rater_name, rating)
      values (
        restaurant_id,
        actor_email,
        actor_name,
        (rating_json ->> 'rating')::numeric
      );
    end if;

    imported_count := imported_count + 1;
  end loop;
  return imported_count;
end;
$import_batch$;

revoke all on function public.import_foodlog_batch(uuid, jsonb) from public;
grant execute on function public.import_foodlog_batch(uuid, jsonb) to authenticated;

create table if not exists public.decision_sessions (
  id uuid primary key default gen_random_uuid(),
  title text not null check (length(trim(title)) between 1 and 120),
  notes text not null default '',
  planned_at timestamptz,
  status text not null default 'open' check (status in ('open', 'closed')),
  created_by text not null,
  selected_restaurant_id uuid references public.restaurants(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  decided_at timestamptz
);

create table if not exists public.decision_candidates (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.decision_sessions(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete restrict,
  added_by text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by text
);

create unique index if not exists decision_candidates_active_unique
  on public.decision_candidates (session_id, restaurant_id)
  where deleted_at is null;

create table if not exists public.decision_votes (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.decision_sessions(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete restrict,
  voter_email text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by text
);

create unique index if not exists decision_votes_active_unique
  on public.decision_votes (session_id, restaurant_id, lower(voter_email))
  where deleted_at is null;
create index if not exists decision_votes_session_idx
  on public.decision_votes (session_id, restaurant_id)
  where deleted_at is null;

alter table public.decision_sessions enable row level security;
alter table public.decision_candidates enable row level security;
alter table public.decision_votes enable row level security;

grant select on public.decision_sessions, public.decision_candidates, public.decision_votes
to anon, authenticated;
grant insert, update on public.decision_sessions, public.decision_candidates, public.decision_votes
to authenticated;
revoke delete on public.decision_sessions, public.decision_candidates, public.decision_votes
from anon, authenticated;

create policy "Public can read decision sessions"
on public.decision_sessions for select to anon, authenticated
using (true);
create policy "Approved editors can create decision sessions"
on public.decision_sessions for insert to authenticated
with check (
  public.is_approved_editor()
  and lower(created_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
);
create policy "Session creators can update decision sessions"
on public.decision_sessions for update to authenticated
using (
  public.is_approved_editor()
  and (
    public.is_foodlog_owner()
    or lower(created_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  )
)
with check (
  public.is_foodlog_owner()
  or lower(created_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
);

create policy "Public can read active decision candidates"
on public.decision_candidates for select to anon, authenticated
using (deleted_at is null);
create policy "Approved editors can add decision candidates"
on public.decision_candidates for insert to authenticated
with check (
  public.is_approved_editor()
  and deleted_at is null
  and lower(added_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  and exists (
    select 1 from public.decision_sessions
    where decision_sessions.id = decision_candidates.session_id
      and decision_sessions.status = 'open'
  )
  and exists (
    select 1 from public.restaurants
    where restaurants.id = decision_candidates.restaurant_id
      and restaurants.deleted_at is null
  )
);
create policy "Candidate contributors can update decision candidates"
on public.decision_candidates for update to authenticated
using (
  public.is_approved_editor()
  and exists (
    select 1 from public.decision_sessions
    where decision_sessions.id = decision_candidates.session_id
      and decision_sessions.status = 'open'
      and (
        public.is_foodlog_owner()
        or lower(decision_sessions.created_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
        or lower(decision_candidates.added_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
      )
  )
)
with check (public.is_approved_editor());

create policy "Approved editors can read active decision votes"
on public.decision_votes for select to authenticated
using (deleted_at is null and public.is_approved_editor());
create policy "Public can aggregate active decision votes"
on public.decision_votes for select to anon
using (deleted_at is null);
create policy "Approved editors can cast their votes"
on public.decision_votes for insert to authenticated
with check (
  public.is_approved_editor()
  and deleted_at is null
  and lower(voter_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  and exists (
    select 1
    from public.decision_sessions
    join public.decision_candidates
      on decision_candidates.session_id = decision_sessions.id
     and decision_candidates.restaurant_id = decision_votes.restaurant_id
     and decision_candidates.deleted_at is null
    where decision_sessions.id = decision_votes.session_id
      and decision_sessions.status = 'open'
  )
);
create policy "Editors can withdraw their votes"
on public.decision_votes for update to authenticated
using (
  public.is_approved_editor()
  and lower(voter_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  and exists (
    select 1 from public.decision_sessions
    where decision_sessions.id = decision_votes.session_id
      and decision_sessions.status = 'open'
  )
)
with check (
  lower(voter_email) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
);

-- Anonymous readers receive public results without exposing voter email addresses.
create or replace view public.decision_vote_totals
with (security_invoker = true, security_barrier = true)
as
select session_id, restaurant_id, count(*)::integer as vote_count
from public.decision_votes
where deleted_at is null
group by session_id, restaurant_id;

revoke all on public.decision_vote_totals from public;
grant select on public.decision_vote_totals to anon, authenticated;
revoke select on public.decision_votes from anon;
grant select (session_id, restaurant_id) on public.decision_votes to anon;

create or replace function private.enforce_three_active_votes()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.deleted_at is null and (
    select count(*)
    from public.decision_votes
    where session_id = new.session_id
      and lower(voter_email) = lower(new.voter_email)
      and deleted_at is null
      and id <> new.id
  ) >= 3 then
    raise exception 'Each person can vote for up to three places.';
  end if;
  return new;
end;
$$;

revoke all on function private.enforce_three_active_votes() from public, anon, authenticated;
drop trigger if exists decision_votes_limit on public.decision_votes;
create trigger decision_votes_limit
before insert or update of deleted_at on public.decision_votes
for each row execute function private.enforce_three_active_votes();

create or replace function public.close_decision_session(p_session_id uuid)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected_id uuid;
begin
  if not exists (
    select 1 from public.decision_sessions
    where id = p_session_id
      and status = 'open'
      and (
        public.is_foodlog_owner()
        or lower(created_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
      )
  ) then
    raise exception 'Only the session creator can close an open session.';
  end if;

  select ranked.restaurant_id
  into selected_id
  from (
    select
      candidates.restaurant_id,
      count(votes.id) as vote_count
    from public.decision_candidates candidates
    left join public.decision_votes votes
      on votes.session_id = candidates.session_id
     and votes.restaurant_id = candidates.restaurant_id
     and votes.deleted_at is null
    where candidates.session_id = p_session_id
      and candidates.deleted_at is null
    group by candidates.restaurant_id
  ) ranked
  order by ranked.vote_count desc, random()
  limit 1;

  if selected_id is null then
    raise exception 'Add at least one place before closing the session.';
  end if;

  update public.decision_sessions
  set
    status = 'closed',
    selected_restaurant_id = selected_id,
    decided_at = now(),
    updated_at = now()
  where id = p_session_id;

  return selected_id;
end;
$$;

create or replace function public.reopen_decision_session(p_session_id uuid)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.decision_sessions
  set
    status = 'open',
    selected_restaurant_id = null,
    decided_at = null,
    updated_at = now()
  where id = p_session_id
    and (
      public.is_foodlog_owner()
      or lower(created_by) = lower(coalesce((select auth.jwt() ->> 'email'), ''))
    );

  if not found then
    raise exception 'Only the session creator can reopen this session.';
  end if;
end;
$$;

revoke all on function public.close_decision_session(uuid) from public;
revoke all on function public.reopen_decision_session(uuid) from public;
grant execute on function public.close_decision_session(uuid) to authenticated;
grant execute on function public.reopen_decision_session(uuid) to authenticated;

drop trigger if exists decision_sessions_activity on public.decision_sessions;
create trigger decision_sessions_activity
after insert or update on public.decision_sessions
for each row execute function private.log_foodlog_row_change('decision_sessions');
drop trigger if exists decision_candidates_activity on public.decision_candidates;
create trigger decision_candidates_activity
after insert or update on public.decision_candidates
for each row execute function private.log_foodlog_row_change('decision_candidates');
drop trigger if exists decision_votes_activity on public.decision_votes;
create trigger decision_votes_activity
after insert or update on public.decision_votes
for each row execute function private.log_foodlog_row_change('decision_votes');

-- Harden existing trigger functions flagged by the database advisor.
alter function public.normalize_pending_approval_email() set search_path = '';
revoke all on function public.normalize_pending_approval_email() from public, anon, authenticated;
revoke all on function public.sync_auth_user_to_pending() from public, anon, authenticated;
revoke all on function public.sync_editor_profile_from_auth() from public, anon, authenticated;
revoke all on function public.sync_restaurant_lookups() from public, anon, authenticated;
